version: '3'

services:
  proxy:
    build: 
      context: ./nginx
    image: nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
  
  app:
    build:
      context: node
    container_name: app
    networks:
    - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    #command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    #volumes:
    #  - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge